### ISSUE TITLE
how to fix "Error: Cannot find module '../akashacms-booknav' "?

### ISSUE THREAD

**Issue by luckypoem** [akashacms/akashacms-blog-skeleton#1]
hi.

root@AR:/usr/local/akashacms-blog-skeleton# akashacms build
module.js:472
    throw err;
    ^

Error: Cannot find module '../akashacms-booknav'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.config (/usr/local/akashacms-blog-skeleton/config.js:107:41)
    at Object.module.exports.config (/usr/local/akashacms-blog-skeleton/node_modules/akashacms/index.js:144:16)
    at Command.<anonymous> (/usr/local/lib/node_modules/akashacms-cli/cli.js:107:16)
    at Command.listener (/usr/local/lib/node_modules/akashacms-cli/node_modules/commander/index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (/usr/local/lib/node_modules/akashacms-cli/node_modules/commander/index.js:615:12)
    at Command.parse (/usr/local/lib/node_modules/akashacms-cli/node_modules/commander/index.js:458:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/akashacms-cli/cli.js:399:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
root@AR:/usr/local/akashacms-blog-skeleton# 

tks a lot

**Comment by robogeek** [comment]
Try again -- obviously require('../akashacms-booknav') was the wrong thing to do.  It's now referencing the package correctly.
